MODULE PROBLEM_DATA

    IMPLICIT NONE
!.....STATE     TRANSITION TENSOR
    LOGICAL,  PARAMETER:: P_STM       = .FALSE. !COMPUTE STATE     TRANSITION TENSOR SENSITIVITY
    INTEGER,  PARAMETER:: P_ORDER     =  4     !0 OR 1 OR 2 OR 3STATE TRANSITITION TENSOR ORDER

!.....CONSTANT DECLARATIONS
    INTEGER,  PARAMETER:: MAX_DERIV_ORDER = 4
    INTEGER,  PARAMETER:: DERIV_ORDER     = P_ORDER !OCEA REQUESTED DERIVATIVE ORDER
    INTEGER,  PARAMETER:: N_STATES        = 6 !NUMBER OF STATE VARIABLES TO BE INTEGRATED( DXDT = F(X,T,P) )

    INTEGER,  PARAMETER:: N_AUXIL         = 0 !NUMBER OF USER-SUPPLIED DIFFERENTIAL EQUATIONS
    INTEGER,  PARAMETER:: NV              = N_STATES  !NUMBER OF INDEPENDENT OCEA VARIABLES
    INTEGER,  PARAMETER:: NSD2            = N_STATES/2
    
    INTEGER,  PARAMETER:: NF              = NV
    
    INTEGER,  PARAMETER:: NOCEA           = 0 
!.....STATE + IC + PARAMETER SENSITIVITY
    INTEGER,  PARAMETER:: NC              = 10 !NUMBER OF CONSTANTS
!.....SELECT PRECISION FOR SINGLE- AND DOUBLE-PRECISION REALS
    INTEGER,  PARAMETER:: SP              = KIND(1.0)
    INTEGER,  PARAMETER:: DP              = selected_real_kind(15,300)
!.....DEFINE KIND TYPE FOR DEFAULT LOGICAL
    INTEGER,  PARAMETER:: LGT             = KIND(.TRUE.)
!.....MATHEMATICAL CONSTANTS
    real(dp), parameter:: pi              = 3.14159265358979323846264d0
    real(dp), parameter:: pio2            = 1.57079632679489661923132d0
    REAL(dp), parameter:: ZERO = 0.0D0, ONE  = 1.0D0  
!.....IO FILE NUMBERS
    INTEGER,  PARAMETER:: ECHO_INPUT      = 10 !FOR file = 'ECHO_INPUT.DAT'
    INTEGER,  PARAMETER:: ERROR_HISTORY   = 15 !FOR FILE = 'ERROR_HISTORY'
    INTEGER,  PARAMETER:: SYS_SIMULATION  = 20 !FOR FILE = 'SYS_SIMULATION.DAT'
    INTEGER,  PARAMETER:: TIME_HISTORY    = 30 !FOR FILE = 'INTEG_HISTORY.DAT'
    INTEGER,  PARAMETER:: STM_HISTORY     = 35 !FOR FILE = 'TIME_HISTORY.DAT'
    INTEGER,  PARAMETER:: TESTING         = 40 !FOR FILE = 'TESTING.DAT'
    INTEGER,  PARAMETER:: JUNK            = 50 !FOR FILE = 'JUNK.DAT'  
    INTEGER,  PARAMETER:: STM_1st_vec     = 51 ! FOR STM_1st_vec 
    INTEGER,  PARAMETER:: StateTime       = 52 ! FOR state time history for matlab check 
    INTEGER,  PARAMETER:: STM_2nd_vec     = 53 ! FOR STM_2nd_vec
    INTEGER,  PARAMETER:: STM_3rd_vec     = 54 ! FOR STM_rd_vec 
    INTEGER,  PARAMETER:: STM_4TH_vec     = 59 ! FOR STM_rd_vec 
    INTEGER,  PARAMETER:: SYMPLECTIC_STM_1ST = 55 ! SYMPLECTIC CHECK FOR STM 1ST 
    INTEGER,  PARAMETER:: SYMPLECTIC_STM_2ND = 56 ! SYMPLECTIC CHECK FOR STM 2ND 
    INTEGER,  PARAMETER:: SYMPLECTIC_STM_3RD = 57 ! SYMPLECTIC CHECK FOR STM 3RD
    INTEGER,  PARAMETER:: SYMPLECTIC_STM_4TH = 58 ! SYMPLECTIC CHECK FOR STM 4TH
    
    
    INTEGER,  PARAMETER:: Final_Time_STM_1st_vec     = 70 ! FOR STM_1st_vec 
    INTEGER,  PARAMETER:: Final_Time_STM_2nd_vec     = 71 ! FOR STM_2nd_vec
    INTEGER,  PARAMETER:: Final_Time_STM_3rd_vec     = 72 ! FOR STM_rd_vec 
    INTEGER,  PARAMETER:: Final_Time_STM_4th_vec     = 73 ! FOR STM_rd_vec 
    
    
    INTEGER,  PARAMETER:: SAVE_SYMPLECTIC_STM_1ST = 41 ! SYMPLECTIC CHECK FOR STM 1ST 
    INTEGER,  PARAMETER:: SAVE_SYMPLECTIC_STM_2ND = 42 ! SYMPLECTIC CHECK FOR STM 2ND 
    INTEGER,  PARAMETER:: SAVE_SYMPLECTIC_STM_3RD = 43 ! SYMPLECTIC CHECK FOR STM 3RD    
    INTEGER,  PARAMETER:: SAVE_SYMPLECTIC_STM_4TH = 44 ! SYMPLECTIC CHECK FOR STM 4TH

!.....INTEGRATION CONTROL PARAMETERS
    REAL(DP)           :: TIME                  !CURRENT TIME IN SIMULATION
    REAL(DP), PARAMETER:: T0      =   0.0D0     !INITIAL INTEGRATION TIME
    REAL(DP), PARAMETER:: TF      = 6.7066D03       !5.0D0    !FINAL   INTEGRATION TIME !67066D03
    INTEGER , PARAMETER:: NSTEPS  =  300  !NUMBER OF INTEGRATION STEPS !300
    REAL(DP), PARAMETER:: DT = (TF-T0)/FLOAT(NSTEPS)!CURRENT INTEGRATION STEP SIZE
    real(dp), parameter:: mu_e    = 3.986004418000000d14 !3.986012d5   !earth gravitational constant  KM^3/S^2
    
    INTEGER            :: NPRT    =   1 ! 10        !NUMBER OF INTEGRATION STEPS SKIPPED FOR PRINTING
    INTEGER            :: PASS                  !INTEGRATION STAGE NUMBER
    REAL(DP), DIMENSION(4):: D0, DC             !RK4 INTEGRATION WEIGHTS (NOTE: DELT NOT PASSED)
    
    CHARACTER(LEN=12)  :: iFMT = '(A/,5I5)'
!                                123456789012345678901    
    CHARACTER(LEN=21)  :: rFMT = '(A/,1000(10E13.5/))'
    
    !.....CONSTANT DECLARATIONS FOR THE GRAVITY
    INTEGER,  PARAMETER:: Max_Degree = 210
    INTEGER,  PARAMETER:: DEG = 10
    real(dp), parameter:: MU  = 3.986004418000000d14
    real(dp), parameter:: REQ = 6378137.0d0
    
END MODULE PROBLEM_DATA